apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.externalDatabase.host | quote }}
  DB_PORT: {{ .Values.externalDatabase.port | quote }}
  DB_NAME: {{ .Values.externalDatabase.database | quote }}
  DB_USER: {{ .Values.externalDatabase.user | quote }}
