apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
      }
      
      location ~ /\. {
        deny all;
        return 404;
      }

      location /api {
        proxy_pass http://{{ .Values.backend.serviceName }}.default.svc.cluster.local:{{ .Values.backend.servicePort }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Origin $http_origin;
        proxy_set_header X-Original-URI $request_uri;
        proxy_redirect off;
      }
    }
